import { Injector } from '@angular/core';
import { BaseTabComponent, NotificationsService } from 'tabby-core';
import { BianbuMcpService } from './mcp.service';
/** @hidden */
export declare class BianbuCloudFilesTabComponent extends BaseTabComponent {
    private mcp;
    private notifications;
    currentPath: string;
    pathInput: string;
    asRoot: boolean;
    busy: boolean;
    items: any[];
    filteredItems: any[];
    selectedPath: string;
    selectedContent: string;
    newDirectoryName: string;
    newFileName: string;
    status: string;
    dragActive: boolean;
    searchText: string;
    history: string[];
    historyIndex: number;
    selectedIndex: number;
    renameTarget: string;
    renameValue: string;
    constructor(injector: Injector, mcp: BianbuMcpService, notifications: NotificationsService);
    ngOnInit(): void;
    get breadcrumbs(): string[];
    get selectedItem(): any | null;
    onKeyDown(event: KeyboardEvent): void;
    refresh(): Promise<void>;
    applyFilter(): void;
    navigateToInput(): Promise<void>;
    navigate(path: string, pushHistory?: boolean): void;
    navigateBreadcrumb(index: number): void;
    goBack(): void;
    goForward(): void;
    goUp(): void;
    moveSelection(delta: number): void;
    selectItem(item: any): void;
    openItem(item: any): Promise<void>;
    saveSelected(): Promise<void>;
    createDirectory(): Promise<void>;
    createFile(): Promise<void>;
    startRename(item: any): void;
    cancelRename(): void;
    commitRename(item: any): Promise<void>;
    deleteItem(item: any): Promise<void>;
    uploadFile(event: Event): Promise<void>;
    uploadDroppedFile(file: File): Promise<void>;
    onDragOver(event: DragEvent): void;
    onDragLeave(): void;
    onDrop(event: DragEvent): Promise<void>;
    downloadSelected(): Promise<void>;
    private joinPath;
    private readFileAsBase64;
}
