import { Injector } from '@angular/core';
import { BaseTabComponent, NotificationsService, PlatformService } from 'tabby-core';
import { BianbuMcpService } from './mcp.service';
interface TransferItem {
    id: number;
    name: string;
    direction: 'upload' | 'download';
    status: 'queued' | 'running' | 'done' | 'error' | 'cancelled';
    bytesDone: number;
    bytesTotal: number | null;
    startedAt: number;
    finishedAt?: number;
    error?: string;
    controller?: AbortController;
}
/** @hidden */
export declare class BianbuCloudFilesTabComponent extends BaseTabComponent {
    private mcp;
    private notifications;
    private platform;
    currentPath: string;
    pathInput: string;
    asRoot: boolean;
    busy: boolean;
    items: any[];
    filteredItems: any[];
    selectedPath: string;
    selectedContent: string;
    selectedIsText: boolean;
    status: string;
    dragActive: boolean;
    searchText: string;
    history: string[];
    historyIndex: number;
    selectedIndex: number;
    contextMenuVisible: boolean;
    contextMenuX: number;
    contextMenuY: number;
    contextItem: any;
    promptVisible: boolean;
    promptTitle: string;
    promptPlaceholder: string;
    promptValue: string;
    promptAction: null | 'mkdir' | 'newfile' | 'rename';
    promptTarget: any;
    transfersVisible: boolean;
    transfers: TransferItem[];
    private transferSeq;
    private transferQueue;
    private transferQueueRunning;
    constructor(injector: Injector, mcp: BianbuMcpService, notifications: NotificationsService, platform: PlatformService);
    ngOnInit(): void;
    get breadcrumbs(): string[];
    get selectedItem(): any | null;
    onDocumentClick(): void;
    onKeyDown(event: KeyboardEvent): void;
    refresh(): Promise<void>;
    applyFilter(): void;
    navigateToInput(): void;
    navigate(path: string, pushHistory?: boolean): void;
    navigateBreadcrumb(index: number): void;
    goBack(): void;
    goForward(): void;
    goUp(): void;
    moveSelection(delta: number): void;
    selectItem(item: any): void;
    openItem(item: any): Promise<void>;
    saveSelected(): Promise<void>;
    openCreateDirectoryPrompt(): void;
    openCreateFilePrompt(): void;
    openRenamePrompt(item: any): void;
    closePrompt(): void;
    confirmPrompt(): Promise<void>;
    createDirectory(name: string): Promise<void>;
    createFile(name: string): Promise<void>;
    renameItem(item: any, name: string): Promise<void>;
    deleteItem(item: any): Promise<void>;
    showContextMenu(event: MouseEvent, item: any): void;
    hideContextMenu(): void;
    uploadFile(event: Event): Promise<void>;
    private createTransfer;
    cancelTransfer(transfer: TransferItem): void;
    transferPercent(transfer: TransferItem): number | null;
    transferRate(transfer: TransferItem): string;
    uploadDroppedFile(file: File): Promise<void>;
    onDragOver(event: DragEvent): void;
    onDragLeave(): void;
    onDrop(event: DragEvent): Promise<void>;
    downloadSelected(): Promise<void>;
    private enqueueUpload;
    private enqueueDownload;
    private queueTransferJob;
    private pumpTransferQueue;
    private runUploadTransfer;
    private runDownloadTransfer;
    private clearPreview;
    baseName(path: string): string;
    private isTextLike;
    private joinPath;
    private uint8ToBase64;
    private base64ToUint8;
}
export {};
